---
# Workaround https://github.com/ansible/ansible/issues/34505
# by not using include_tasks
- name: Restart all Pulp services
  include: handlers/restart_all_pulp.yml
  static: no

- name: Collect static content
  command: "{{ pulp_django_admin_path }} collectstatic --noinput --link {{ pulp_collectstatic_ignore_list }}"
  register: staticresult
  changed_when: "staticresult.stdout is not search('\n0 static files')"
  become: true
  become_user: '{{ pulp_user }}'
  # Restarting pulpcore-api is necessary for collectstatic to
  # work; whitenoise cannot see the files unless pulpcore-api is restarted.
  #
  notify: Restart all Pulp services
  environment:
    PULP_SETTINGS: "{{ pulp_settings_file }}"
